config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/customers/new', to: 'customers#new'
  post '/customers', to: 'customers#create'

  get '/customers', to: 'customers#index'

  get '/customers/:id/edit', to: 'customers#edit', as: 'edit_customer'
  patch '/customers/:id', to: 'customers#update', as: 'update_customer'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :gender, inclusion: { in: %w(male female) }, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customers = Customer.new
  end

  def index
    @customers = Customer.all
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:success] = "Customer was successfully updated"
        redirect_to customers_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def salutation_gender(gender)
    case gender
    when 'male'
      'Mr.'
    when 'female'
      'Ms.'
    else
      ''
    end
  end
end

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= form_with(model: @customer, url: update_customer_path(@customer), local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :gender %>
    <%= form.select :gender, ['male', 'female', 'other'] %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<h1>Customers List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%=salutation_gender(customer.gender)%><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.gender %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1>Add New Customer</h1>

<%= form_with(model: Customer.new, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :gender %>
    <%= form.select :gender, ['male', 'female', 'other'] %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripPlanning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>